### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Track your counters online with real-time sharing and seamless collaboration!
tagline: Effortlessly create, rename, and delete counters while enjoying automatic online synchronization. Share counters with friends, family, or colleagues to collaborate in real time – perfect for tracking shared goals or inventories.

email: syncedcounter.application@gmail.com
description: Effortlessly create, rename, and delete counters while enjoying automatic online synchronization. Share counters with friends, family, or colleagues to collaborate in real time – perfect for tracking shared goals or inventories.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://syncedcounter.app" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#FF191C1D'
github_username:  syncedcounter
logo: assets/images/large-logo.png

languages: ["en"]
ampdir: amp

github: false

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#google: verification_code
google_analytics: G-FMPXZRX7B8
doorbell:
  id: 14387
  appKey: 9n4ZqNGQkx9HB385NZzCLc8Q4rcdMVMxssrNOZiFAZ0ie5ZWc5kvTF3IsMWRlu9d

include:
  - ".well-known"

cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
